"""
global stuff
"""

EM_USE_SPECTRUM_SUMLIKE = 0
EM_USE_SUMLIKE = 3
EM_USE_DOA_ONLY = 7


EM_FUSION_SUM = 10
EM_FUSION_PRODUCT = 20

ESTIMATE_SIGMA_INDIVIDUALLY = -1
ESTIMATE_SIGMA_GLOBALLY = -9  